### ISSUE TITLE
Make sure locales can use (soft) hyphenation for added readings in bottom drawer

### ISSUE THREAD

**Issue by TonnesM** [Glucosio/glucosio-android#283]
Today’s daily build scared me a bit, as adding readings apparently may be changed so that (existing) strings will be displayed in a bottom drawer/matrix instead of on top of each other like the tooltips view. However, this causes 3 out of 6 strings to break/wrap at unwanted positions for my locale (14 characters), and possibly others that do not allow spaces in compound nouns, unlike English.

Can/should the following be made possible?
- Add ability for enabling soft hyphenation in the app itself, if needed
- Add new strings for those displayed in the drawer/matrix (i.e. not share them with those below the graph), if needed
- If soft hyphenation is not possible, make sure new strings are added to allow hard hyphenation
- If soft hyphenation is possible and when shared anyway, add context for those strings that may need hyphenation for the drawer (on Crowdin)
- Add context about how to and/or what format to use for soft hyphens (on Crowdin)

**Comment by emartynov** [comment]
Thanks for feedback. What is you locale?

**Comment by TonnesM** [comment]
You’re welcome. It’s Dutch/nl - words that currently break are the 3 longest of course, i.e. Bloedsuikerspiegel, Lichaamsgewicht and Cholesterolspiegel. Allowed hyphenations would happen before "spiegel" and "gewicht", if only we knew how to (e.g using &shy;, &#173, \u00AD, etc.), or hardcoded.

**Comment by TonnesM** [comment]
Any news on this? Can hyphenation be used and how, and if not, how about just adding separate strings for the new ones to use hard hyphens? I think this should definitely be fixed in v.next (and not have been included in v.current.)

**Comment by emartynov** [comment]
It is not yet prioritised. I've checked tech part for android:

- http://stackoverflow.com/questions/4454911/hyphenation-in-android
- https://developer.android.com/reference/android/widget/TextView.html#attr_android:hyphenationFrequency
- https://code.google.com/p/android/issues/detail?id=25755

Still don't have clear picture how to implement it. I will do small spike about it this weekend.

**Comment by TonnesM** [comment]
Thanks for the info - this may be harder than expected. I also found this:

- http://stackoverflow.com/questions/20655186/how-to-add-a-line-break-hint-in-an-android-app-name

Suggestion: why not just add new entries for the drawer for now and allow localizers to add hyphens for those? Localizers could test to find out if an additional space (after the hyphen) is required to let the strings wrap properly (unless you already know) and the issue would be resolved. Investigating hyphenation may take longer than expected and can always be implemented afterwards, if supported by Android at all.

**Comment by TonnesM** [comment]
Any news? Just add 2nd strings to include hardcoded hyphens for now?

**Comment by TonnesM** [comment]
Again, any news? Can’t test myself using dailies either since they obviously don’t use the latest localizations.

**Comment by emartynov** [comment]
@TonnesM I'm trying to apply hyphenation to specific views. Can you make a screenshot of the problem? I switched to German and added pair of readings but can not spot place which you described in original message

**Comment by TonnesM** [comment]
@emartynov Glad to see your reponse. I was about to give up my contributions since the project seems to be dead and the issue was reported 6 months ago (for a daily version, hoping it would prevent the issue to appear in release version), so I was a little disappointed to say the least.

See the screenshot. I added `&#173;` for the first but to no avail. Doesn't (or rather: can) Daily use current localizations to test with?

![glucosio_bad_hyphenation_add_reading](https://cloud.githubusercontent.com/assets/14834507/23201828/978d3d0e-f8db-11e6-8275-9252d3f923ef.png)

**Comment by emartynov** [comment]
@TonnesM, what version of android do you have? I  can make quick changes for Marshmallow and up. However for older version it is not so trivial.

**Comment by TonnesM** [comment]
@emartynov I use 6.0.1/Marshmallow allright, though presumably users should see this fixed for any version if possible, even if it would require 6 additional strings for localizers to include hardcoded hyphens. Assuming Android would hyphenate at that point, though if not, it can be circumvented by adding a space after the hyphen. Sidenote: sharing l10n strings isn’t often a wise thing to do, as you may know.

Sorry for asking again, but shouldn’t daily versions use current approved strings so other methods can be tested by users? Or are strings only imported just prior to release versions?

**Comment by emartynov** [comment]
@TonnesM, I would like to fix the issue for all users. However, that will be possible only with proper translations with special Unicode chars.

As quick development fix is to use better typography added in Marshmallow. 

I can also programmatically calculate width needed for displaying text and add this symbols but it would lead to non-natural breaks.

I need help from Crowdin expert how to instruct translators to add special Unicode char.

**Comment by emartynov** [comment]
Looks like no luck https://code.google.com/p/android/issues/detail?id=203895

**Comment by TonnesM** [comment]
Well, looking at the link above (http://stackoverflow.com/questions/20655186/how-to-add-a-line-break-hint-in-an-android-app-name) and its referred http://stackoverflow.com/questions/13594979/zero-width-line-breaking-space-for-android as well as your recent one above, I’m afraid we’re wasting time here. There seems to be no current solution for implementing proper soft-hyphenation even in current Android releases, regardless of locales or Unicode characters and their support for any of them. Mozilla people couldn’t help me out here either - Benjamin can probably acknowledge. All I know is iOS does support the use of &#173; in XLIFF files, and I still can’t tell what it does in Android unless the question above is answered.

Sidenote: I reported this issue at the point when noticing the issue following out of a new feature (or rather, UI change) in a daily version which caused a regression IMO, not expecting to see this or hoping to have it revoked before a release version. Yet a number of days after, this was implemented in release. That means there is a regression issue users are suffering, and it has been ongoing for 6 months even though some may call it trivial. Moreover, I see more half-implemented features and continuous glitches in Glucosio, and I’m not a fan of that. I’m not a perfectionist, but considering developers are there to instruct computers and software, I’d prefer to see things work as they should before implementing or releasing them, and quickly patched when needed.

Back when I was more involved in coding (which is no longer or never really has been my cup of tea), such changes were sometimes unacceptable, at least for me. If a new feature causes a regression or new issue, implementing it would be a no go. Now I tried to include/provide options to fix this in several ways when opening this issue with a little rush to be honest - both from a user perspective and the technical desire to implement the automation, though I know hyphenation is often a pain in software development and sometimes considered an achievement more than it serves anything in a reliable way. So I think you’ll agree the short-term solution will fix it for now. Implementing soft-hyphenation may be a future ‘mission’ to accomplish, but not at the cost of users, so all we need now is a quick solution that’s way easier to accomplish and may definitely save you time. 

What may have gone wrong is the assumption of English text that fits the UI would cause no issues for other locales (has this been tested anyway?), while it’s a known fact many other locales use longer words (and about 30% more of text, on the average). So if I was to decide, I would either revert to the old “tooltip-like” listing of what type of reading to add, or choose the easy fix for now and probably await Android to support a reliable way of soft-hyphenating.

Additionally, one of my credos is this:

“Computers, bits and the ability to manage them are pretty fast nowadays. It’s usually people or processes slowing them down.”

That means things could sometimes be fixed within 5 minutes (I know some developers don’t like me saying so as a non-dev), but some people like to extend their lifespan, or do so undeliberately. From a technical view I understand that real issues or design implementations may take longer than 5 minutes, but IMO and especially for regressions that would mean:

a) avoid the implementation completely, postpone it or use another approach, or
b) work around it for now and ASAP to “hide” the so-called issue and keep working on the implementation meanwhile, but only if that would ever succeed.

Last and not intended to be rude, I have asked some questions a few times here and still got no reply. I’m not fond of that in general, since in this case it obstructs proper communication, and I can’t help out without those questions answered either. This is not intended as a personal attack, but I hope you’ll understand. I always try to count question marks myself before responding to a thread. ;)

Therefor:

- Do daily versions use currently approved strings or not so localizers with approval rights can change strings and test them in Daily? Meanwhile I don’t think so, but it would be nice if that Daily could use them
- Can you please add 6 separate strings for the drawer strings involved to avoid sharing them with the ones below the graph, so localizers can easily either duplicate content from the existing ones or add a hyphen+space to them to make things look fine? I’m 100% sure they will, even for any Android version. Any indentation on the lower part will be no issue since as you see in English, they will indent anyway, nor will spaces following the hyphen in the upper part be visible. The only question would be is whether or not a word (part) ending with a hyphen would be considered as a normal word and displayed as such, and I think it would.

Thanks.

Creative screenshot with desired view for my locale:

![glucosio_bad_hyphenation_desired](https://cloud.githubusercontent.com/assets/14834507/23413017/afdc6ece-fdd7-11e6-9d21-a6d89ee46b3c.png)

**Comment by TonnesM** [comment]
In case it helps: I was about to report success for the `&#173;` code using the April 13th Daily build (after a new build/import showed up on Crowdin the day before) on Marshmallow that _perfectly_ shows the exact screenshot above while the Overview strings remain untouched, so that this issue could be resolved. 

However, today’s build (April 19th) behaves like a regular version, i.e. offering all locales instead of just one, not requiring a 2nd start to appear localized, but not hyphenating again.

What happened? @emartynov Are you still working on this?

**Comment by emartynov** [comment]
I finished your proposal in the first week of march. Tried to play with API 23 but without luck on emulator and real device. I will finish it this weekend with hardcoded dashes.

**Comment by TonnesM** [comment]
Sorry to say but due lack of activity and response to easy questions more than once, I consider the project to be dead. Is this true?

**Comment by ghost** [comment]
Hi TonnesM our Android lead Dev has not been available much due to university were trying to find a new lead Dev.

**Comment by emartynov** [comment]
Benjamin, I'm responsible for this issue and my fault it is not yet fixed.
